# Prerequisites

source 'https://rubygems.org'

gem 'chunky_png',             '~>1.3.4'
gem 'descriptive_statistics', '~>2.5.1'
gem 'distribution',           '~>0.7.3'
gem 'rubystats',              '~>0.2.3'
gem 'nyaplot',                '~>0.1.6'
gem 'byebug'
